### ISSUE TITLE
Maximum number of simultaneous connections/how to handle?

### ISSUE THREAD

**Issue by alexwhittemore** [adafruit/Adafruit_Blinka_bleio#18]
I'm half-afraid to post this as an "issue" since it's basically a help request, but in the interest of education:

I've got a fleet of feathers, all advertising a UART service. When a UARTClient connects, they periodically print out their data payload. For -as many feathers as I currently own- this works great with the Adafruit Bluefruit Connect app, in "multiple UART mode," which is what I'd like to replicate on a raspberry pi in that same role. 

My first stab at that is the code below:

``` python
import time
from adafruit_ble import BLERadio
from adafruit_ble.advertising.standard import ProvideServicesAdvertisement
from adafruit_ble.services.nordic import UARTService

ble = BLERadio()
while True:
    if ble.connected and any( # This used to be "while ble.connected..." but if we do that, we'll never scan again...
        UARTService in connection for connection in ble.connections
    ):
        for connection in ble.connections:
            print(connection)
            if UARTService not in connection:
                continue
            uart = connection[UARTService]
            one_byte = uart.read()
            if one_byte:
                print(one_byte)
            print()
        #time.sleep(1)

    print("scanning")
    for advertisement in ble.start_scan(ProvideServicesAdvertisement, timeout=1):
        if UARTService in advertisement.services and "MyFeather" in advertisement.complete_name:
            print(advertisement.complete_name)
            ble.connect(advertisement)
            #break
    ble.stop_scan()
```

Given the "while loop"-style flow control, I'm not sure of the best way to simultaneously manage advertising and connection processing. "Scan for one second every loop then stop" obviously leaves something to be desired in terms of both time that can't be used to process UART input and time processing uart input where new devices won't get detected. 

Under most circumstances, the code above works as you'd expect. But it looks like I get connection failures sometimes (`org.bluez.Error.Failed: Software caused connection abort`) I guess maybe if the code tries to ble.connect() towards the end of the scan timeout?

Also, stability seems dependent on the relative timing of the multiple UART messages. Sometimes I seem to see behavior where one UART message consistently gets through and the other consistently doesn't show up, despite both connections appearing in the list - I guess probably because the first doesn't get serviced before the second wipes it out or something?

Anyway long story short, it looks and feels like my strategy above is "bad" and I'm wondering if there's an obvious way to make it less-bad in a circuitpython context. 

Ultimately, I'd like an arbitrarily large fleet that basically wakes up, takes a sample, waits for a "gateway" UARTClient to connect, backhauls the data, then goes back to (deep) sleep for many minutes. 

It MIGHT make sense to ditch connections and UART entirely and adopt an advertising scheme, which is what I sort of originally intended anyway, a-la https://github.com/adafruit/Adafruit_CircuitPython_BLE_BroadcastNet. But I kind of want delivery assurance. The intended scale of the system I'm working on is many hundreds of densely-packed devices trying to backhaul very infrequent data, so if they HAPPEN to be too time-aligned, it seems plausible the flood of advertisements prevents a "gateway" from actually collecting them all. I don't want unheard sensors to go back to sleep, hence "connect, exfil data, sleep" seems like the right strategy.

If you've got thoughts, I'd love to hear them!

**unrelated bonus question:**
Is there a way to get the `advertisement.common_name` as in the "scanning" segment from the `connection` in the UART handling segment? I need to save "data from device 12345" separately from "data from device 54321" and it seems like that would be preferable to "include device ID in the UART payload," but I can't quite figure out how to do that.

**Comment by tannewt** [comment]
> arbitrarily large fleet

I think it'd be good to put an upper limit on your design. You only have so much air time to transfer the samples you'll be taking. Putting an upper limit on your design will let you run numbers on it.

I think your exceptions and stability issues are Linux dependent and I'm not sure how much we'll be able to help.

My bias is obviously BroadcastNet since I designed it. I like it because its simple and easy to provision. It has sequence numbers to measure reliability and can support multiple gateways to reduce missed messages. The one show stopper is if you want to keep the data you transfer private. You'll need connections to do that.

You could possibly simplify your connection approach by disconnecting after you receive the data. That way you only ever have one connection active. You then just scan until you hear a device wanting to offload data, connect, offload and disconnect. Then, you repeat. If you can't keep up, you'll end up with all of the devices advertising.

Another thing to consider is time keeping. If you want all of the samples relative to each other then you'll need a clock source. BroadcastNet fudges the clock by requiring the gateway to provide a time. If you are batching or delaying readings then you may need each sensor to have its own clock.

**Comment by alexwhittemore** [comment]
I'm working with BroadcastNet right now for all those reasons, though haven't fully adapted and tested it yet :). Privacy is a concern of mine, but it isn't actually stipulated by requirements. 

I DID try (later in the day after posting) the "connect/dump/disconnect" strategy, but ran into HUGE stability issues with that as well. Revisiting it now in my head: the issue was that the sensor would get the connection, dump its payload, then disconnect, all before the Pi had a chance to realize it was connected and receive the data. One of two test feathers had a delay built in post-send, pre-disconnect, and the other had a shorter. the longer delay feather got its message across ~100% and the no-delay feather ~0%. I don't really understand the performance issues and cost centers on the RasPi code above, but I guess if I simply built the delay into the Pi side, that would probably solve the reliability issues. I'll have to try that and then experiment with advertisements when I've got more breathing room.

**Comment by dhalbert** [comment]
I'll close this for now but please reopen if needed.

**Comment by alexwhittemore** [comment]
Oh - definitely reasonable, but I should add some more info:

For one, there IS a practical limit on simultaneous connections, different for every device. For the nRF52840 in the Feather Sense, it's softdevice dependent, but theoretically 20. Theoretically, because that would use all the memory on the device, and there'd be nothing left for (in this case circuitpython). I'm guessing CP has a set limit somewhere hardcoded to avoid memory headaches. For more info: https://devzone.nordicsemi.com/f/nordic-q-a/35158/how-many-connections-nrf52840-nrf52832-supports-as-peripheral.

At a slightly higher level, 20 happens to be the highest of any device I've researched. Android seems to set the count at "something like 5" and Apple at "something like 10." The problem is that a tiny real time processor has to maintain all the connection info and service their time requirements (even if sparse), so it doesn't matter that there's a whole OS and GB of ram to use - the tiny chip handling the PHY is what matters. 

Second, as far as connect/dump/disconnect, that IS a reasonable strategy, but as I mentioned above, it's still no guarantee of receipt, without some additional logic on your part. But the bigger issue for my "zillions of devices" use case is that it takes a surprising amount of time - many seconds- to establish a connection. I'm sure a fair amount of that is on-air, too, so zillions of devices advertising to connect all at once probably doesn't scale. I'm not sure how much of the overhead is down to circuitpython/Blinka and could be improved with baremetal code, but I'm not betting it makes enough of a difference anyway.

So ultimately that leaves me with pure advertising and building any necessary privacy/security/delivery assurance on top of that (which IS practical, just difficult).

**Comment by ukBaz** [comment]
> Ultimately, I'd like an arbitrarily large fleet that basically wakes up, takes a sample, waits for a "gateway" UARTClient to connect, backhauls the data, then goes back to (deep) sleep for many minutes

This sounds a lot like the problem Bluetooth mesh is designed to solve:
https://www.novelbits.io/bluetooth-mesh-tutorial-part-1/

**Comment by dhalbert** [comment]
> For the nRF52840 in the Feather Sense, it's softdevice dependent, but theoretically 20. Theoretically, because that would use all the memory on the device, and there'd be nothing left for (in this case circuitpython). I'm guessing CP has a set limit somewhere hardcoded to avoid memory headaches

Yes, we limit the amount used to 56kB. The connection limits, and many other limits are set here: https://github.com/adafruit/circuitpython/blob/main/ports/nrf/common-hal/_bleio/Adapter.c#L127 ff. We did a lot of tuning and experimentation to find out how much increasing each kind of connection cost, the queue sizes, etc.

**Comment by alexwhittemore** [comment]
Ahh, yes, so on the nRF52840 in CircuitPython, it's "5" :)

@ukbaz - In my case, not necessarily. All of the devices only need to send data to a single gateway. Mesh might alleviate a routing headache by distributing connections required over many devices, instead of say 1000 single-connection devices and one 1000-connection gateway. I think the ultimate limit of my setup is just practical air time, and minimizing that. But thanks for the tutorial link anyway - it's very much on my to-do list to learn more.
