### ISSUE TITLE
Does this work on OSX ?

### ISSUE THREAD

**Issue by stormbytes** [adafruit/Adafruit_Blinka_bleio#35]
Just found the previous version of this library which explicitly states it works with OSX. I'm not a Python coder so maybe this is a dumb question, but can this be used on Mac OSX ?

**Comment by dhalbert** [comment]
Yes, it was tested on "MacOS", including Big Sur. A good place for support questions like these is in the forums https://forums.adafruit.com, or our discord server, https://adafru.it/discord.

**Comment by stormbytes** [comment]
Super! Thanks for the tip. Will check there for support.
