### ISSUE TITLE
Improved Typing

### ISSUE THREAD

**Issue by davclark** [adafruit/Adafruit_Blinka_bleio#43]
As of today, installing the requirements in python 3.9.11 on Linux (Kubuntu 21.10) plus mypy, and running `mypy _bleio` yields 58 errors.

@dhalbert pointed me to the C bindings: https://github.com/adafruit/circuitpython/tree/main/shared-bindings/_bleio

**Comment by FoamyGuy** [comment]
The specific mypy errors that we are interested in knocking out with our first round of effort are the "missing annotations for function arguments or return" 

mypy can flag other things as well but we're trying to get the bulk of those missing typing altogether done and then eventually down the line we may add mypy checks to the actions CI and at that time we'll figure out the configuration to use which will affect which specific errors end up getting flagged for us.

**Comment by dhalbert** [comment]
Fixed by #44.
